export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const DEL_PRODUCT_SUCCESS = "DEL_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_SUCCESS ="EDIT_PRODUCT_SUCCESS"